name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: fhidalgoc-org/.github/.github/workflows/blank.yml@main
    name: run reusable workflow
    with:
      name: hello_from_template
    
      personal_access_token: ${{ secrets.GITHUB_TOKEN }}

