name: checkout_and_setup

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization

  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install dependencies
        run: pip install ultralytics