name: checkout_and_setup

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  # build:
  #   name: checkout
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Run a one-line script
  #       run: echo Hello from Octo Organization

  # setup:
  #   name: setup
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: setup python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.10.16

  #     # - name: install dependencies
  #     #   run: pip install ultralytics

  #     # - name: export model
  #     #   run: yolo export model=yolo11n.pt format=onnx
  #     #   shell: bash

  release-please:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # skip-github-pull-request: true
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple


